# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zrAvo2Snc61dRCnEvcVY_4ZqyVRThom9

**Data Science and Business Analytics Internship**

**Task 1: Prediction using Supervised ML**

Problem Statement-What will be  predicted score if a student studies for 9.25 hrs/day

demonstrated and performed by **Priya Srivastava**
"""

#Importing the libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Reading data
url="http://bit.ly/w-data"
data=pd.read_csv(url)

#reading the first five value of dataset
data.head()

# plotting the distribution of score
data.plot(x='Hours',y='Scores',style='o')
plt.title('Hours vs Percentage')
plt.xlabel('Hours studied')
plt.ylabel('percentage score')
plt.show()

#dividing the data into inputs and outputs
X=data.iloc[:, :-1].values
y=data.iloc[:,1].values

#Splitting data into test and train datasets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#training model
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

#Linear Regression
line=regressor.coef_*X+regressor.intercept_
plt.scatter(X,y)
plt.plot(X,line);
plt.show()

print(X_test)

#Predicting the scores
y_pred=regressor.predict(X_test)

#comparing
df=pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df

#predicting the score
dataset=np.array(9.25)
dataset=dataset.reshape(-1,1)
pred=regressor.predict(dataset)
print("if studied for 9.25 hours per day, score will be {}.".format(pred))

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test,y_pred))